package ru.dyatel.tsuschedule.events

enum class Event {

    DATA_MODIFIER_SET_CHANGED, DATA_UPDATED, DATA_UPDATE_FAILED,

    DISABLE_NAVIGATION_DRAWER, ENABLE_NAVIGATION_DRAWER,

    PREFERENCES_LATEST_VERSION_CHANGED,

    NAVIGATION_TO

}
