package ru.dyatel.tsuschedule.events

enum class Event {

    INITIAL_DATA_FETCH,

    DATA_MODIFIER_SET_CHANGED, DATA_UPDATED, DATA_UPDATE_FAILED,

    SET_TOOLBAR_SHADOW_ENABLED,
    DISABLE_NAVIGATION_DRAWER, ENABLE_NAVIGATION_DRAWER,

    PREFERENCES_LATEST_VERSION_CHANGED,

    NAVIGATION_TO

}
