package ru.dyatel.tsuschedule.events

enum class Event {

    INITIAL_DATA_FETCH,

    DATA_MODIFIER_SET_CHANGED, DATA_UPDATED, DATA_UPDATE_FAILED,

    SET_TOOLBAR_SHADOW_ENABLED, SET_DRAWER_ENABLED,

    PREFERENCES_LATEST_VERSION_CHANGED,

    ADD_GROUP

}
